export const BANK_NAMES: Record<string, string> = {
  'ICB': 'VietinBank',
  'VCB': 'Vietcombank',
  'BIDV': 'BIDV',
  'VBA': 'Agribank',
  'OCB': 'OCB',
  'MB': 'MBBank',
  'TCB': 'Techcombank',
  'ACB': 'ACB',
  'VPB': 'VPBank',
  'TPB': 'TPBank',
  'STB': 'Sacombank',
  'HDB': 'HDBank',
  'VCCB': 'VietCapitalBank',
  'SCB': 'SCB',
  'VIB': 'VIB',
  'SHB': 'SHB',
  'EIB': 'Eximbank',
  'MSB': 'MSB',
  'CAKE': 'CAKE',
  'Ubank': 'Ubank',
  'VTLMONEY': 'ViettelMoney',
  'TIMO': 'Timo',
  'VNPTMONEY': 'VNPTMoney',
  'SGICB': 'SaigonBank',
  'BAB': 'BacABank',
  'momo': 'MoMo',
  'PVDB': 'PVcomBank Pay',
  'PVCB': 'PVcomBank',
  'MBV': 'MBV',
  'NCB': 'NCB',
  'SHBVN': 'ShinhanBank',
  'ABB': 'ABBANK',
  'VAB': 'VietABank',
  'NAB': 'NamABank',
  'PGB': 'PGBank',
  'VIETBANK': 'VietBank',
  'BVB': 'BaoVietBank',
  'SEAB': 'SeABank',
  'COOPBANK': 'COOPBANK',
  'LPB': 'LPBank',
  'KLB': 'KienLongBank',
  'KBank': 'KBank',
  'MAFC': 'MAFC',
  'HLBVN': 'HongLeong',
  'KEBHANAHN': 'KEBHANAHN',
  'KEBHANAHCM': 'KEBHanaHCM',
  'CITIBANK': 'Citibank',
  'CBB': 'CBBank',
  'CIMB': 'CIMB',
  'DBS': 'DBSBank',
  'Vikki': 'Vikki',
  'VBSP': 'VBSP',
  'GPB': 'GPBank',
  'KBHCM': 'KookminHCM',
  'KBHN': 'KookminHN',
  'WVN': 'Woori',
  'VRB': 'VRB',
  'HSBC': 'HSBC',
  'IBK - HN': 'IBKHN',
  'IBK - HCM': 'IBKHCM',
  'IVB': 'IndovinaBank',
  'UOB': 'UnitedOverseas',
  'NHB HN': 'Nonghyup',
  'SCVN': 'StandardChartered',
  'PBVN': 'PublicBank',
};
